import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Maqro task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="snap max-h-screen snap-y snap-proximity overflow-y-scroll">
          <section className="flex h-screen w-full snap-start bg-red-200">
            <div className="m-auto">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Et
              excepturi voluptatem vero commodi recusandae, eos, quia nesciunt
              accusamus cupiditate alias perferendis ea ut voluptas explicabo.
              Necessitatibus ex doloremque accusantium eum!
            </div>
          </section>
          <section className="flex h-screen w-full snap-start bg-blue-200">
            <div className="m-auto">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Et
              excepturi voluptatem vero commodi recusandae, eos, quia nesciunt
              accusamus cupiditate alias perferendis ea ut voluptas explicabo.
              Necessitatibus ex doloremque accusantium eum!
            </div>
          </section>
          <section className="flex h-screen w-full snap-start bg-green-200">
            <div className="m-auto ">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Et
              excepturi voluptatem vero commodi recusandae, eos, quia nesciunt
              accusamus cupiditate alias perferendis ea ut voluptas explicabo.
              Necessitatibus ex doloremque accusantium eum!
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
